/**
 * @file MMU.h
 * @author created by: Peter Hlavaty
 */

#ifndef __MMU_HEADERS_H__
#define __MMU_HEADERS_H__

#include "../base/Common.h"

struct VIRTUAL_ADDRESS
{
	union
	{
		void* Address;
		struct
		{
			ULONG_PTR ByteOffset : PAGE_SHIFT;
			ULONG_PTR PTESelector : 9;
			ULONG_PTR PTSelector : 9;
			ULONG_PTR PDPSelector : 9;
			ULONG_PTR PML4Selector : 9;
		} Selector;
		struct
		{
			ULONG_PTR ExtendedByteOffset : 21;
			ULONG_PTR PTSelector : 9;
			ULONG_PTR PDPSelector : 9;
			ULONG_PTR PML4Selector : 9;
		} LPSelector;
	};
};

struct PAGE_TABLE_ENTRY
{
	ULONG_PTR Valid : 1;
	ULONG_PTR Write : 1;
	ULONG_PTR Owner : 1;
	ULONG_PTR WriteTrough : 1;
	ULONG_PTR CacheDisabled : 1;
	ULONG_PTR Accessed : 1;
	ULONG_PTR Dirty : 1;
	ULONG_PTR LargePage : 1;
	ULONG_PTR Global : 1;
	ULONG_PTR SWCopyOnWrite : 1;
	ULONG_PTR SWPrototypePTE : 1;
	ULONG_PTR SWWrite : 1;
	ULONG_PTR PageFrameNumber : 28;
	ULONG_PTR Reserved : 12;
	ULONG_PTR SWWorkingSetIndex : 11;
	ULONG_PTR NoExecute : 1;
};

//dd nt!MmProtectToValue
//http://www.reactos.org/pipermail/ros-diffs/2010-October/038897.html
static ULONG const MmProtectToValue[32] = {
	PAGE_NOACCESS,
	PAGE_READONLY,
	PAGE_EXECUTE,
	PAGE_EXECUTE_READ,
	PAGE_READWRITE,
	PAGE_WRITECOPY,
	PAGE_EXECUTE_READWRITE,
	PAGE_EXECUTE_WRITECOPY,
	PAGE_NOACCESS,
	PAGE_NOCACHE | PAGE_READONLY,
	PAGE_NOCACHE | PAGE_EXECUTE,
	PAGE_NOCACHE | PAGE_EXECUTE_READ,
	PAGE_NOCACHE | PAGE_READWRITE,
	PAGE_NOCACHE | PAGE_WRITECOPY,
	PAGE_NOCACHE | PAGE_EXECUTE_READWRITE,
	PAGE_NOCACHE | PAGE_EXECUTE_WRITECOPY,
	PAGE_NOACCESS,
	PAGE_GUARD | PAGE_READONLY,
	PAGE_GUARD | PAGE_EXECUTE,
	PAGE_GUARD | PAGE_EXECUTE_READ,
	PAGE_GUARD | PAGE_READWRITE,
	PAGE_GUARD | PAGE_WRITECOPY,
	PAGE_GUARD | PAGE_EXECUTE_READWRITE,
	PAGE_GUARD | PAGE_EXECUTE_WRITECOPY,
	PAGE_NOACCESS,
	PAGE_WRITECOMBINE | PAGE_READONLY,
	PAGE_WRITECOMBINE | PAGE_EXECUTE,
	PAGE_WRITECOMBINE | PAGE_EXECUTE_READ,
	PAGE_WRITECOMBINE | PAGE_READWRITE,
	PAGE_WRITECOMBINE | PAGE_WRITECOPY,
	PAGE_WRITECOMBINE | PAGE_EXECUTE_READWRITE,
	PAGE_WRITECOMBINE | PAGE_EXECUTE_WRITECOPY
};

enum
{
	PAGE_EXE_MASK = 0xF0,
	PAGE_WR_MASK = 0xCC,
	PAGE_WR_COPY = 0x88,
};

#endif //__MMU_HEADERS_H__
